const assets = {
  icons: {
    arrow_down: "/icons/arrow_down.svg",
    arrow_left: "/icons/arrow_left.svg",
    arrow_right: "/icons/arrow_right.svg",
    arrow_right_gray: "/icons/arrow_right_gray.svg",
    check: "/icons/check.svg",
    email: "/icons/mail.svg",
    phone: "/icons/phone.svg",
    location: "/icons/location.svg",
    search: "/icons/search.svg",
    cart: "/icons/cart.svg",
    double_user: "/icons/double_user.svg",
    hamburger_menu: "/icons/hamburger_menu.svg",
    checkout: "/icons/checkout.svg",
    checkout_white: "/icons/checkout_white.svg",
    calender: "/icons/calender.svg",
    cart_purple: "/icons/cart_purple.svg",
    plus: "/icons/plus.svg",
    delete: "/icons/delete.svg",
    close: "/icons/close.svg",
    account: "/icons/account.svg",
    orders: "/icons/orders.svg",
    payment: "/icons/payments.svg",
    notification: "/icons/notification.svg",
    help: "/icons/help.svg",
    settings: "/icons/setting.svg",
    logout: "/icons/logout.svg",
    edit: "/icons/edit.svg",
    receipt_purple: "/icons/receipt_purple.svg",
    export: "/icons/export.svg",
    receipt: "/icons/receipt.svg",
    card_purple: "/icons/card_purple.svg",
    paypal: "/icons/paypal.svg",
    mastercard: "/icons/mastercard.svg",
    bin_purple: "/icons/bin_purple.svg",
    location_purple: "/icons/location_purple.svg",
    admin: "/icons/admin.svg",
    products: "/icons/products.svg",
    users: "/icons/users.svg",
    analytics: "/icons/analytics.svg",
    dashboard: "/icons/dashboard.svg",
    bin: "/icons/bin.svg",
    upload: "/icons/upload.svg",
    signup: "/icons/signup.svg",
    green_tickmark: "/icons/green_tickmark.svg",
    home: "/icons/home.svg",
    work: "/icons/work.svg",
    villa: "/icons/villa.svg",
    plus_purple: "/icons/plus_purple.svg",
    payments_purple: "/icons/payments_purple.svg",
    processing: "/icons/processing.svg",
    shipping: "/icons/shipping.svg",
    delivered: "/icons/delivered.svg",
    pending: "/icons/pending.svg",
    search_purple: "/icons/search_purple.svg",
    cart_white: "/icons/cart_white.svg",
    filter: "/icons/filter.svg",
    card: "/icons/card.svg",
    red_fail: "/icons/red_fail.svg",
  },
  onboarding: {
    step1: {
      mushroom: "/images/mushroom.png",
      fish: "/images/fish.png",
      ham: "/images/ham.png",
      meat: "/images/meat.png",
      sphagetti: "/images/sphagetti.png",
      shrimp: "/images/shrimp.png",
      pizza: "/images/pizza.png",
      chicken: "/images/chicken.png",
    },
  },
  logo: "/icons/logo.svg",
  socials: {
    google: "/icons/google.svg",
    meta: "/icons/meta.svg",
  },
  home: {
    two_column_grid: {
      frame1: "/images/home-images/two-column-grid-images/frame1.png",
      frame2: "/images/home-images/two-column-grid-images/frame2.png",
      frame3: "/images/home-images/two-column-grid-images/frame3.png",
      frame4: "/images/home-images/two-column-grid-images/frame4.png",
      frame5: "/images/home-images/two-column-grid-images/frame5.png",
    },
    category_strip: {
      fruits: "/images/home-images/category-strip/fruits.png",
      vegetables: "/images/home-images/category-strip/vegetables.png",
      meatPoultry: "/images/home-images/category-strip/meat_poultry.png",
      dairyProducts: "/images/home-images/category-strip/dairy_products.png",
      bakery: "/images/home-images/category-strip/bakery.png",
      seafood: "/images/home-images/category-strip/seafood.png",
      breakfast: "/images/home-images/category-strip/breakfast.png",
      pasta_noodles: "/images/home-images/category-strip/pasta_noodles.png",
      grains: "/images/home-images/category-strip/grains.png",
    },
  },
};

export default assets;
