const assets = {
  icons: {
    arrow_down: "/icons/arrow_down.svg",
    arrow_left: "/icons/arrow_left.svg",
    arrow_right: "/icons/arrow_right.svg",
    arrow_right_gray: "/icons/arrow_right_gray.svg",
    check: "/icons/check.svg",
    email: "/icons/mail.svg",
    phone: "/icons/phone.svg",
    location: "/icons/Location.svg",
    search: "/icons/Search.svg",
    cart: "/icons/cart.svg",
    double_user: "/icons/double_user.svg",
    hamburger_menu: "/icons/hamburger_menu.svg",
    checkout: "/icons/checkout.svg",
    checkout_white: "/icons/checkout_white.svg",
    calender: "/icons/calender.svg",
    cart_purple: "/icons/cart_purple.svg",
    plus: "/icons/plus.svg",
    delete: "/icons/delete.svg",
  },
  onboarding: {
    step1: {
      mushroom: "/images/mushroom.png",
      fish: "/images/fish.png",
      ham: "/images/ham.png",
      meat: "/images/meat.png",
      sphagetti: "/images/sphagetti.png",
      shrimp: "/images/shrimp.png",
      pizza: "/images/pizza.png",
      chicken: "/images/chicken.png",
    },
  },
  logo: "/icons/logo.svg",
  socials: {
    google: "/icons/google.svg",
    meta: "/icons/meta.svg",
  },
  home: {
    two_column_grid: {
      frame1: "/images/home-images/two-column-grid-images/frame1.png",
      frame2: "/images/home-images/two-column-grid-images/frame2.png",
      frame3: "/images/home-images/two-column-grid-images/frame3.png",
      frame4: "/images/home-images/two-column-grid-images/frame4.png",
      frame5: "/images/home-images/two-column-grid-images/frame5.png",
    },
    category_strip: {
      drinks: "/images/home-images/category-strip/drinks.png",
      carrot: "/images/home-images/category-strip/carrot.png",
      cans: "/images/home-images/category-strip/cans.png",
      cheese: "/images/home-images/category-strip/cheese.png",
      yoghurt: "/images/home-images/category-strip/yoghurt.png",
      watermelon: "/images/home-images/category-strip/watermelon.png",
      cake: "/images/home-images/category-strip/cake.png",
      bread: "/images/home-images/category-strip/bread.png",
      snacks: "/images/home-images/category-strip/snacks.png",
      apple: "/images/home-images/category-strip/apple.png",
      vegetables: "/images/home-images/category-strip/vegetables.png",
      candy: "/images/home-images/category-strip/candy.png",
    },
    best_sellers: {
      img1: "/images/home-images/best-seller/img1.png",
      img2: "/images/home-images/best-seller/img2.png",
      img3: "/images/home-images/best-seller/img3.png",
    },
  },
};

export default assets;
